### ISSUE TITLE
Dialyzer action always rebuilds PLT even on "cache hit"

### ISSUE THREAD

**Issue by digitalcora** [mbta/actions#12]
See here for an example: https://github.com/mbta/alerts_concierge/runs/2853235786

The output says "Cache hit, not building PLT", but Dialyzer proceeds to rebuild the PLT anyway. It seems to always do this, even on commits where no code has changed. When I run Dialyzer locally, it does work (says "PLT is up to date!" and skips the rebuild, completing in ~10 seconds).

**Comment by digitalcora** [comment]
I think this might be the issue:

https://github.com/mbta/actions/blob/74467267665c8eb29916e3da1e321806e0b803f6/dialyzer/src/main.ts#L84

I'm running Dialyzer in `MIX_ENV=test` (to save time by not also compiling the `dev` environment), but this line results in only the PLTs for the `dev` environment being saved in the cache.

**Comment by paulswartz** [comment]
That seems reasonable. I've run into issues with running Dialyzer against the test environment, but if it's working for you then we can update the paths to also fetch test PLTs.

**Comment by digitalcora** [comment]
The only change I had to make was adding `plt_add_apps: [:ex_unit]` to the config, since ExUnit is not among the apps Dialyzer adds by default, and it otherwise complains about some functions "not existing". But yeah, it works fine. I think the cache path could just be `_build/*/*.plt*`.
